name: problem_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy==1.24.3
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - plotly==5.15.0
    - dash==2.11.1
    - dash-bootstrap-components==1.4.2
    - flask==2.3.2
    - requests==2.31.0
    - python-dotenv==1.0.0
    - jupyter==1.0.0
    - ipykernel==6.25.0
    - notebook==7.0.2
    - pytest==7.4.0
    - black==23.7.0
    - flake8==6.1.0
    - isort==5.12.0 